# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mdlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(max_length=25)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContentTypeLog', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuariLog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_log',
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
