# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 18:31
from __future__ import unicode_literals

import app.track_management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mdlTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='GPS name of track.', max_length=4000)),
                ('cmt', models.TextField(blank=True, help_text='GPS comment for track.', null=True)),
                ('desc', models.TextField(blank=True, help_text='ser description of track.', null=True)),
                ('src', models.CharField(blank=True, help_text='Source of data. Included to give user some idea of reliability and accuracy of data.', max_length=100, null=True)),
                ('link', models.URLField(blank=True, help_text='Links to external information about track.', null=True)),
                ('number', models.IntegerField(default=1, help_text='GPS track number.')),
                ('type', models.CharField(blank=True, help_text='Type (classification) of track.', max_length=100, null=True)),
                ('hash_code', models.CharField(blank=True, db_index=True, default=app.track_management.models._createHash, max_length=32, null=True)),
                ('deleted', models.BooleanField(default=False, help_text='Is the track deleted?')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuari_soci', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'track',
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
