# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdlgpxtracksegmentpoint',
            name='gpx_track',
        ),
        migrations.AddField(
            model_name='mdlgpxtracksegmentpoint',
            name='gpx_track_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track_management.mdlGPXTrackSegment'),
        ),
        migrations.AlterField(
            model_name='mdlgpxtracksegment',
            name='segmentLine',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
