# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:36
from __future__ import unicode_literals

import app.track_management.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4000, verbose_name='Title')),
                ('gpx_file', models.FileField(blank=True, upload_to=app.track_management.models.GPX_Folder)),
            ],
        ),
        migrations.CreateModel(
            name='GPXPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_management.gpxFile')),
            ],
        ),
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_management.gpxFile')),
            ],
        ),
        migrations.RemoveField(
            model_name='mdltrack',
            name='cmt',
        ),
        migrations.RemoveField(
            model_name='mdltrack',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='mdltrack',
            name='link',
        ),
        migrations.RemoveField(
            model_name='mdltrack',
            name='number',
        ),
        migrations.RemoveField(
            model_name='mdltrack',
            name='src',
        ),
        migrations.AddField(
            model_name='mdltrack',
            name='description',
            field=models.TextField(blank=True, help_text='User description of track.', null=True),
        ),
        migrations.AlterField(
            model_name='mdltrack',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mdltrack',
            name='type',
            field=models.CharField(blank=True, choices=[('gpx', 'GPX'), ('f', 'Female'), ('u', 'Undefined')], help_text='Track type.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_management.mdlTrack'),
        ),
    ]
