# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_management', '0002_auto_20160127_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gpxFile',
            new_name='mdlGPXFile',
        ),
        migrations.RenameModel(
            old_name='GPXPoint',
            new_name='mdlGPXPoint',
        ),
        migrations.RenameModel(
            old_name='GPXTrack',
            new_name='mdlGPXTrack',
        ),
        migrations.AlterField(
            model_name='mdltrack',
            name='type',
            field=models.CharField(blank=True, choices=[('gpx', 'GPX'), ('klm', 'KLM'), ('fir', 'FIT')], help_text='Track type.', max_length=3, null=True),
        ),
    ]
