# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_management', '0002_auto_20160205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlgpxroute',
            name='trackLine',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mdlgpxtrack',
            name='trackLine',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
