# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_management', '0003_auto_20160128_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdlgpxfile',
            options={'verbose_name': 'GPX_File', 'verbose_name_plural': 'GPX_Files'},
        ),
        migrations.AlterModelOptions(
            name='mdlgpxpoint',
            options={'verbose_name': 'GPX_Point', 'verbose_name_plural': 'GPX_Points'},
        ),
        migrations.AlterModelOptions(
            name='mdlgpxtrack',
            options={'verbose_name': 'GPX_Track', 'verbose_name_plural': 'GPX_Tracks'},
        ),
        migrations.AlterModelTable(
            name='mdlgpxfile',
            table='GPX_File',
        ),
        migrations.AlterModelTable(
            name='mdlgpxpoint',
            table='GPX_Point',
        ),
        migrations.AlterModelTable(
            name='mdlgpxtrack',
            table='GPX_Track',
        ),
    ]
